// Generated by CoffeeScript 1.8.0
(function() {
  require(["jquery"], function($) {
    return $(function() {
      var Corner, state;
      $(window).on("contextmenu", function(e) {
        return e.preventDefault();
      });
      Corner = (function() {
        function Corner(button, frame, list, row, col) {
          this.button = button;
          this.frame = frame;
          this.list = list;
          this.row = row;
          this.col = col;
          this.visible = false;
          this.button.on("click", (function(_this) {
            return function() {
              _this.activate(true);
              _this.halfHeight(_this.list[(_this.row + 1) % 2][_this.col].visible);
              _this.halfWidth(_this.list[(_this.row + 1) % 2][_this.col].visible || _this.list[0][(_this.col + 1) % 2].visible || _this.list[1][(_this.col + 1) % 2].visible);
              _this.list[(_this.row + 1) % 2][_this.col].halfHeight(true).halfWidth(true);
              _this.list[0][(_this.col + 1) % 2].halfWidth(true);
              return _this.list[1][(_this.col + 1) % 2].halfWidth(true);
            };
          })(this));
          this.frame.on("quit", (function(_this) {
            return function() {
              _this.activate(false);
              _this.list[(_this.row + 1) % 2][_this.col].halfHeight(false).halfWidth(_this.list[0][(_this.col + 1) % 2].visible || _this.list[1][(_this.col + 1) % 2].visible);
              _this.list[0][(_this.col + 1) % 2].halfWidth(_this.list[(_this.row + 1) % 2][_this.col].visible || _this.list[1][(_this.col + 1) % 2].visible);
              return _this.list[1][(_this.col + 1) % 2].halfWidth(_this.list[0][(_this.col + 1) % 2].visible || _this.list[(_this.row + 1) % 2][_this.col].visible);
            };
          })(this));
        }

        Corner.prototype.activate = function(flag) {
          this.visible = flag;
          this.button.toggleClass("hidden", flag);
          this.frame.toggleClass("hidden", !flag);
          return this;
        };

        Corner.prototype.halfWidth = function(flag) {
          this.frame.toggleClass("half-width", flag);
          return this;
        };

        Corner.prototype.halfHeight = function(flag) {
          this.frame.toggleClass("half-height", flag);
          return this;
        };

        return Corner;

      })();
      state = [[], []];
      state[0][0] = new Corner($(".join.top.left"), $(".frame.top.left"), state, 0, 0);
      state[0][1] = new Corner($(".join.top.right"), $(".frame.top.right"), state, 0, 1);
      state[1][0] = new Corner($(".join.bottom.left"), $(".frame.bottom.left"), state, 1, 0);
      return state[1][1] = new Corner($(".join.bottom.right"), $(".frame.bottom.right"), state, 1, 1);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
