// Generated by CoffeeScript 1.7.1
(function() {
  require(["jquery"], function($) {
    return $(function() {
      var fbl, fbr, ftl, ftr, jbl, jbr, jtl, jtr;
      $(window).on("contextmenu", function(e) {
        return e.preventDefault();
      });
      jtl = $(".join.top.left");
      jtr = $(".join.top.right");
      jbr = $(".join.bottom.right");
      jbl = $(".join.bottom.left");
      ftl = $(".frame.top.left");
      ftr = $(".frame.top.right");
      fbr = $(".frame.bottom.right");
      fbl = $(".frame.bottom.left");
      jbl.on("click", function() {
        jbl.addClass("hidden");
        fbl.removeClass("hidden").attr("src", "page.html");
        return jtr.removeClass("hidden");
      });
      jtr.on("click", function() {
        jtr.addClass("hidden");
        fbl.addClass("half-width");
        fbr.addClass("half-width");
        ftl.addClass("half-width");
        ftr.addClass("half-width").removeClass("hidden").attr("src", "page.html");
        jtl.removeClass("hidden");
        return jbr.removeClass("hidden");
      });
      jtl.on("click", function() {
        jtl.addClass("hidden");
        fbl.addClass("half-height");
        return ftl.addClass("half-height").removeClass("hidden").attr("src", "page.html");
      });
      return jbr.on("click", function() {
        jbr.addClass("hidden");
        ftr.addClass("half-height");
        return fbr.addClass("half-height").removeClass("hidden").attr("src", "page.html");
      });
    });
  });

}).call(this);

//# sourceMappingURL=index.map
