// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    baseUrl: "js/",
    paths: {
      "underscore": "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore",
      "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery",
      "mousewheel": "https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.12/jquery.mousewheel",
      "paper": "https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.9.21/paper-core"
    }
  });

}).call(this);

//# sourceMappingURL=require-config.js.map
