// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    baseUrl: "js/",
    paths: {
      "jquery": "../lib/jquery",
      "paper": "../lib/paper-core"
    }
  });

}).call(this);

//# sourceMappingURL=require-config.js.map
