// Generated by CoffeeScript 1.8.0
(function() {
  define(function() {
    return {
      images: [
        {
          image: "accuracy/img/image.jpg",
          reference: "accuracy/img/reference.png",
          width: 1920,
          height: 1280
        }
      ]
    };
  });

}).call(this);

//# sourceMappingURL=config.js.map
