// Generated by CoffeeScript 1.8.0
(function() {
  define(["paper"], function(paper) {
    var Raster, Size;
    Raster = paper.Raster, Size = paper.Size;
    if (window.painter == null) {
      window.painter = {};
    }
    return (function() {
      function _Class(canvas) {
        paper.setup(canvas);
        this.project = paper.project;
        this.view = this.project.view;
        this.raster = new Raster({
          visible: false
        });
        this.raster.on("load", (function(_this) {
          return function() {
            return _this.raster.setVisible(true);
          };
        })(this));
      }

      _Class.prototype.show = function(image, size) {
        this.raster.setSource(image);
        this.raster.setPosition(new Size(size).divide(2));
        return this;
      };

      _Class.prototype.hide = function() {
        this.raster.setVisible(false);
        this.view.draw();
        return this;
      };

      return _Class;

    })();
  });

}).call(this);

//# sourceMappingURL=Image.js.map
