// Generated by CoffeeScript 1.8.0
(function() {
  define(["./Image", "./Path", "./Position", "./Zoom"], function(Image, Path, Position, Zoom) {
    return (function() {
      function _Class(image, path, position) {
        this.image = new Image(image);
        this.path = new Path(path);
        this.position = new Position(position);
        this.zoomer = new Zoom([this.image.view, this.path.view, this.position.view]);
      }

      _Class.prototype.showImage = function(image, width, height) {
        this.image.show(image, [width, height]);
        this.zoomer.setBounds([0, 0, width, height]);
        return this;
      };

      _Class.prototype.hideImage = function() {
        this.image.hide();
        return this;
      };

      _Class.prototype.setTool = function(_arg) {
        var color, size, tool;
        tool = _arg.tool, color = _arg.color, size = _arg.size;
        this.path.setTool(tool);
        this.position.setColor(color);
        this.path.setColor(color);
        this.position.setSize(size);
        this.path.setSize(size);
        return this;
      };

      _Class.prototype.setName = function(name) {
        this.position.setText(name);
        return this;
      };

      _Class.prototype.setPoint = function(point) {
        this.position.draw(point);
        this.path.add(point);
        return this;
      };

      _Class.prototype.hidePosition = function() {
        this.position.hide();
        return this;
      };

      _Class.prototype.showPosition = function() {
        this.position.show();
        return this;
      };

      _Class.prototype.hidePath = function() {
        this.path.hide();
        return this;
      };

      _Class.prototype.showPath = function() {
        this.path.show();
        return this;
      };

      _Class.prototype.beginPath = function() {
        this.path.begin();
        return this;
      };

      _Class.prototype.endPath = function() {
        this.path.end();
        return this;
      };

      _Class.prototype.resize = function(width, height) {
        var size;
        size = [width, height];
        this.image.view.setViewSize(size);
        this.path.view.setViewSize(size);
        this.position.view.setViewSize(size);
        return this;
      };

      _Class.prototype.fit = function() {
        this.zoomer.fit();
        return this;
      };

      _Class.prototype.zoom = function(zoom, center) {
        this.zoomer.zoom(zoom, center);
        return this;
      };

      _Class.prototype.scale = function(scale, center) {
        this.zoomer.scale(scale, center);
        return this;
      };

      _Class.prototype.scroll = function(vector) {
        this.zoomer.scroll(vector);
        return this;
      };

      _Class.prototype.absolutePoint = function(point) {
        return this.zoomer.absolutePoint(point);
      };

      return _Class;

    })();
  });

}).call(this);

//# sourceMappingURL=Painter.js.map
